name: scardini
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - _python_abi3_support=1.0
  - anyio=4.11.0
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.4.0
  - asttokens=3.0.1
  - async-lru=2.0.5
  - attrs=25.4.0
  - babel=2.17.0
  - beautifulsoup4=4.14.2
  - bleach=6.3.0
  - bleach-with-css=6.3.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - colorama=0.4.6
  - comm=0.2.3
  - cpython=3.14.0
  - debugpy=1.8.17
  - decorator=5.2.1
  - defusedxml=0.7.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - fqdn=1.5.1
  - h11=0.16.0
  - h2=4.3.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - idna=3.11
  - importlib-metadata=8.7.0
  - importlib_resources=6.5.2
  - ipykernel=7.1.0
  - ipython=9.7.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.8
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - json5=0.12.1
  - jsonpointer=3.0.0
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jsonschema-with-format-nongpl=4.25.1
  - jupyter=1.1.1
  - jupyter-lsp=2.3.0
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.9.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.5.0
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.28.0
  - jupyterlab_widgets=3.0.16
  - krb5=1.21.3
  - lark=1.3.1
  - libblas=3.11.0
  - libcblas=3.11.0
  - libexpat=2.7.3
  - libffi=3.5.2
  - libhwloc=2.12.1
  - libiconv=1.18
  - liblapack=3.11.0
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libsodium=1.0.20
  - libsqlite=3.51.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - llvm-openmp=21.1.6
  - markupsafe=3.0.3
  - matplotlib-inline=0.2.1
  - mistune=3.1.4
  - mkl=2025.3.0
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - notebook=7.5.0
  - notebook-shim=0.2.4
  - numpy=2.3.5
  - openssl=3.6.0
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.3.3
  - pandocfilters=1.5.0
  - parso=0.8.5
  - pip=25.3
  - platformdirs=4.5.0
  - prometheus_client=0.23.1
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - psutil=7.1.3
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.2
  - pysocks=1.7.1
  - python=3.14.0
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-gil=3.14.0
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python_abi=3.14
  - pytz=2025.2
  - pywin32=311
  - pywinpty=2.0.15
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - referencing=0.37.0
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rpds-py=0.29.0
  - send2trash=1.8.3
  - setuptools=80.9.0
  - six=1.17.0
  - sniffio=1.3.1
  - soupsieve=2.8
  - stack_data=0.6.3
  - tbb=2022.3.0
  - terminado=0.18.1
  - tinycss2=1.5.0
  - tk=8.6.13
  - tomli=2.3.0
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - tzdata=2025b
  - ucrt=10.0.26100.0
  - uri-template=1.3.0
  - urllib3=2.5.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - wcwidth=0.2.14
  - webcolors=25.10.0
  - webencodings=0.5.1
  - websocket-client=1.9.0
  - widgetsnbextension=4.0.15
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - afrc==0.3.7
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - biopython==1.86
      - contourpy==1.3.3
      - cycler==0.12.1
      - cython==3.2.1
      - filelock==3.20.0
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - getsequence==2.2.1
      - idptools-parrot==1.7.6+3.g0c2d4e4.dirty
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - lightning-utilities==0.15.2
      - localcider==0.1.21
      - matplotlib==3.10.7
      - metapredict==3.0.1
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - multidict==6.7.0
      - networkx==3.5
      - pillow==12.0.0
      - propcache==0.4.1
      - protfasta==0.1.15.2
      - pyfamsa==0.6.1
      - pyparsing==3.2.5
      - pytorch-lightning==2.5.6
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - scoring-matrices==0.3.3
      - seaborn==0.13.2
      - sparrow==0.2.2+55.g2a9b8a0
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - torch==2.9.1
      - torchmetrics==1.8.2
      - tqdm==4.67.1
      - yarl==1.22.0
